kind: pipeline
name: default

steps:

  - name: build-image
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build -t print-headers-nodejs:1.0.0.0 .
