kind: pipeline
name: default

steps:

  - name: Build image
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build --no-cache -t print-headers-nodejs .
